default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test
  username: postgres
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: d4pfpn49hl1id9